---
title: "Visualization"
subtitle: "part II"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
```

Load in a dataset that we we'll use often. 

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Remember this plot..?
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)
```

## Labels

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperatue plot",
    x = "Minimum daily temerpature (C)",
    y = "Maximum daily temperature (C)", 
    caption = "Data from rnoaa package; temperatures in 2017."
    )
```

## Scales

start with the same plot 

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperatue plot",
    x = "Minimum daily temperatue (C)",
    y = "Maximum daily temperature (C)", 
    caption = "Data from rnoa package; temperature in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE)
```
